[package]
name = "my-tasks"
version = "0.1.0"
authors = ["Jérôme"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.2", features = ["macros", "rt"]}
uuid = "0.8"
reqwest = "0.11"
minidom = "0.13"
url = "2.2"
