[package]
name = "my-tasks"
version = "0.1.0"
authors = ["Jérôme"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = "0.8"
